# Generated by Django 6.0.7 on 2026-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField(unique=True)),
                ('resting_hr', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('moderate_min', models.IntegerField(blank=True, null=True)),
                ('vigorous_min', models.IntegerField(blank=True, null=True)),
                ('avg_stress', models.IntegerField(blank=True, null=True)),
                ('bb_charged', models.IntegerField(blank=True, null=True)),
                ('bb_drained', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('zip', 'Export GDPR (zip)'), ('api', 'API Garmin Connect')], max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'journée',
                'verbose_name_plural': 'journées',
                'ordering': ['calendar_date'],
            },
        ),
        migrations.CreateModel(
            name='SleepNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField(unique=True)),
                ('start_gmt', models.DateTimeField()),
                ('end_gmt', models.DateTimeField()),
                ('deep_s', models.IntegerField(default=0)),
                ('light_s', models.IntegerField(default=0)),
                ('rem_s', models.IntegerField(blank=True, null=True)),
                ('awake_s', models.IntegerField(default=0)),
                ('unmeasurable_s', models.IntegerField(default=0)),
                ('awake_count', models.IntegerField(blank=True, null=True)),
                ('avg_sleep_stress', models.FloatField(blank=True, null=True)),
                ('restless_moments', models.IntegerField(blank=True, null=True)),
                ('avg_spo2', models.FloatField(blank=True, null=True)),
                ('lowest_spo2', models.IntegerField(blank=True, null=True)),
                ('avg_sleep_hr', models.FloatField(blank=True, null=True)),
                ('score_overall', models.IntegerField(blank=True, null=True)),
                ('score_quality', models.IntegerField(blank=True, null=True)),
                ('score_duration', models.IntegerField(blank=True, null=True)),
                ('score_recovery', models.IntegerField(blank=True, null=True)),
                ('score_deep', models.IntegerField(blank=True, null=True)),
                ('score_rem', models.IntegerField(blank=True, null=True)),
                ('score_feedback', models.TextField(blank=True, null=True)),
                ('score_insight', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('zip', 'Export GDPR (zip)'), ('api', 'API Garmin Connect')], max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nuit',
                'verbose_name_plural': 'nuits',
                'ordering': ['calendar_date'],
            },
        ),
    ]
